### ISSUE TITLE
Reduce app.js.map size from assets

### ISSUE THREAD

**Issue by nicohsieh** [adamgruber/mochawesome-report-generator#101]
I noticed that in the generated `assets` folder,`app.js.map` is 1.8 mb and it doesn't look it has much benefit? Or maybe just use a `cheap-source-map` to serve debug purpose with a lighter size? Just a minor clean up suggestion. I'm using `mochawesome@3.0.2` and `mochawesome-report-generator@3.1.2`

**Comment by adamgruber** [comment]
Probably should just omit the sourcemaps when publishing.

**Comment by adamgruber** [comment]
Fixed in 3.1.3
