### ISSUE TITLE
Auto expand option for context

### ISSUE THREAD

**Issue by nicohsieh** [adamgruber/mochawesome-report-generator#102]
I looked through the doc but didn't see this option available. I'd like see if there is a possibility for a `contextAutoExpand` option. In the tests I'm working on, the screenshot images are important references, and visually it will make more sense it they are auto expanded.

**Comment by adamgruber** [comment]
This looks like a duplicate of https://github.com/adamgruber/mochawesome/issues/217

**Comment by nicohsieh** [comment]
Indeed this is a duplicate of adamgruber/mochawesome#217 I was only searching issues within this repo. Closing the issue.
