### ISSUE TITLE
How to add sub-content in the report 

### ISSUE THREAD

**Issue by alnvny** [adamgruber/mochawesome-report-generator#112]
![image](https://user-images.githubusercontent.com/12086660/46516370-ecded700-c886-11e8-9a32-5af5883f400c.png)

I need to add sub-headers with time stand in the report.

**Comment by alnvny** [comment]
I just want to find a way to add content marked in square red. How did you add this?

**Comment by adamgruber** [comment]
That information is populated automatically based on the name of your suite and test file. There's currently no option to add more info here.
