### ISSUE TITLE
A retried test doesn't appear in the report when still failed (mocha)

### ISSUE THREAD

**Issue by Stephane99** [adamgruber/mochawesome-report-generator#129]
Hello,

I add a retry option on a test which is run with mocha.
When this test is failed, after a retry, it appears in the json file with following status:
                "pass": false,
                "fail": false,
                "pending": false,
                ...
                "skipped": true

So I can see duration, and number of failed test = 1 on top of the report, but I can't see the detail of test. It doesn't appear in the report's body.

Example:

describe(
    'Test retries on describe', function () {
      this.retries(1);

      it('always failed test', function () {
        expect(1).to.equal(2);
      });
}

You can find the full json report here: 
https://gist.github.com/Stephane99/57f23fd5938f71e2e7e49fe9eb543e58

**Comment by Stephane99** [comment]
Sorry, it's not an error on mochawesome-report-generator but mochawesome and I found other issues on this problem.

**Comment by SharkBaby** [comment]
@Stephane99  Could you please share how do you fix this problem ? as I got same issue as well. thanks
