### ISSUE TITLE
[request] Expose internal MochawesomeReport React components for rendering test results

### ISSUE THREAD

**Issue by Clairly** [adamgruber/mochawesome-report-generator#132]
Hi! Love the reports, this is great! I'm working on a project to render test run histories on an internal dashboard, but I'm running into issues embedding the generated HTML/JS in a React component. I noticed this library uses React under the hood, so I'm wondering if you could expose the MochawesomeReport component (or a standalone) as an importable React component. It would accept the mochawesome JSON as input.

Thanks!

**Comment by luisasalas** [comment]
Same here, I would love to load this report inside of our internal QA dashboard.

**Comment by adamgruber** [comment]
I'm  not sure how feasible this is right now. The report is more than just a React component, it's basically a single page app. It might let you view the results but you'd lose all functionality.
