### ISSUE TITLE
React and React DOM should be peer deps

### ISSUE THREAD

**Issue by jooj123** [adamgruber/mochawesome-report-generator#141]
React and React DOM should be peer deps so that consuming apps dont run into issues with multiple version of react causing issues like:

If i run `npm ls react` from my node server i get a duplicate version of react:
```
└─┬ mochawesome@3.1.1
  └─┬ mochawesome-report-generator@3.1.5
    └── react@16.9.0
```

If this was a peerDep then it would ensure that only 1 version of react is used by a consumer of mochawesome-report-generator
Most libraries / tools are setup this way when using react

**Comment by adamgruber** [comment]
I agree this change should be made however I'm unsure if its considered breaking or not. Feels like it could be a breaking change and thus require a major version bump.

**Comment by mfolnovic** [comment]
any progress on this? :see_no_evil:

**Comment by adamgruber** [comment]
This is updated in `5.0.0`
