### ISSUE TITLE
Can't open old version's reports

### ISSUE THREAD

**Issue by Saeed-Ataee** [adamgruber/mochawesome-report-generator#146]
I was using version 3.1.5. Now I update the module to 4.1.0. The reports generate correctly. But old reports generated by old version does not load in html file. `app.js` and `app.css` changes does not support old reports?

[image](https://gofile.io/?c=sE6aN8)

How can I handle this?

**Comment by adamgruber** [comment]
After updating and generating new reports, it should have also generated new app.js and app.css files. There were breaking changes between those versions.

**Comment by Saeed-Ataee** [comment]
Is there a way to handle old reports? Should I reproduce All of them again? @adamgruber

**Comment by SamuelVinay91** [comment]
@adamgruber  - We are facing the same issue ,Is there any fix coming up ?

**Comment by adamgruber** [comment]
Can you give me a better example of what’s going on? Is it old html files but the newer app.js?

**Comment by SamuelVinay91** [comment]
@adamgruber  - Yes,we updated to latest version 6.1.1 but previous HTML files were not getting open .I doubt due to breakages between previous app.js and latest app.js

**Comment by SamuelVinay91** [comment]
@adamgruber - Any Update on this?

**Comment by adamgruber** [comment]
@SamuelVinay91 As I said earlier this is due to breaking changes with the data structure between versions. In order to open older reports you will need to use an older `app.js` file. You can download this from unpkg.com (https://unpkg.com/browse/mochawesome-report-generator@3.1.2/dist/app.js).

**Comment by SamuelVinay91** [comment]
@adamgruber  - Thank you !!
