### ISSUE TITLE
unable to view screenshot in the report

### ISSUE THREAD

**Issue by Amrkamel1** [adamgruber/mochawesome-report-generator#147]
screenshot picture are appearing empty and api shows 404, im not sure where exactly screenshots folder from cypress should be located in order to make mohcaawsome recognize it 

![image](https://user-images.githubusercontent.com/32042806/82071018-cd9c6280-96d5-11ea-976a-b3827b9a1e22.png)

![image](https://user-images.githubusercontent.com/32042806/82071285-2ec43600-96d6-11ea-8ac9-9b7744780875.png)

![image](https://user-images.githubusercontent.com/32042806/82071367-4bf90480-96d6-11ea-9a08-eb4768e1860e.png)

**Comment by Amrkamel1** [comment]
solved by adjusting name pattern for macha json  in support/index.js

**Comment by dillibabukannan** [comment]
Please help me to resolve this issue as I am also facing the same issue as mentioned above.  Please let me know the steps to resolve this issue. Failed screenshot present under cypress/reports/mochareports/assets, also I could see the screen shot attached in the mochawesome report but getting <ERR_FILE_NOT_FOUND> when trying to access it.

**Comment by mudit94** [comment]
any update on this?
