### ISSUE TITLE
Optmize for thousands of test cases

### ISSUE THREAD

**Issue by luochen1990** [adamgruber/mochawesome-report-generator#15]
I have 2600+ test cases, and the generated `mochawesome.html` file needs 14 seconds to be opened by Chrome.  

Is there any idea to optmize it?  

PS: The generated `mochawesome.html` file is 10MB and `mochawesome.json` is 8.2MB

**Comment by adamgruber** [comment]
I'm certainly open to any ideas you have for reducing size.

**Comment by adamgruber** [comment]
I just released v3.0.0 which includes enhancements to reduce the overall file sizes and improve perceived rendering.
