### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by justinzelinsky** [adamgruber/mochawesome-report-generator#161]
Can we cut a new release so I open a PR in [mochawesome](https://github.com/adamgruber/mochawesome) to include the security fix?

**Comment by adamgruber** [comment]
What was the security issue?

**Comment by justinzelinsky** [comment]
In [this](https://github.com/adamgruber/mochawesome-report-generator/pull/159) PR I bumped `opener` to resolve an [issue](https://securitylab.github.com/advisories/GHSL-2020-145-domenic-opener) with it. `mochawesome` has this lib as a dependency and I want to update that once we have a new release available.

**Comment by adamgruber** [comment]
5.2.0 released and mochawesome 6.2.2 released with updated dependency
