### ISSUE TITLE
Filenames with hashes

### ISSUE THREAD

**Issue by hoeni** [adamgruber/mochawesome-report-generator#162]
A spec file named `No error for empty date (#2302)` with a spec `Clear date without error` produces an image named `No error for empty date (#2302) -- Clear date without error (failed).png` which does not seem to be escaped correctly in the HTML (image not found). When I remove the hash it works.

Normally I'd say, don't care about idiots with hashes in identifiers 🤣, but they are rather common as denotations of ticket numbers which often lead to specs.

**Comment by adamgruber** [comment]
Can you provide a repo where this issue is reproduced?

**Comment by hoeni** [comment]
Sorry, looks like I can't reproduce this.
