### ISSUE TITLE
Access data from report.json

### ISSUE THREAD

**Issue by milindm7** [adamgruber/mochawesome-report-generator#166]
I tried accessing report.json in After block but getting error as 
Error: ENOENT: No such for or directory, open ‘../../../reports/mochaawesome-report/report.json’

Could you please help and let me know if it is possible to access this file and data from this file inside JS code?

Thank you!

**Comment by adamgruber** [comment]
I'm not really clear on what you are trying to do but it could just be a typo in the path. Should be `mochawesome` with one "a".

**Comment by milindm7** [comment]
I have use exact path. I am trying to read from report.json using fileReadSync but getting error as file not found.

**Comment by adamgruber** [comment]
I may be missing something here. Sounds like you are trying to read from `report.json` inside a test? How would that work? The JSON file doesn't exist until the test run is complete.

**Comment by milindm7** [comment]
> I may be missing something here. Sounds like you are trying to read from `report.json` inside a test? How would that work? The JSON file doesn't exist until the test run is complete.

I am trying that in After block inside test. Is JSON file created even after After block of test?

**Comment by adamgruber** [comment]
The `after` block runs after all tests have completed but before the report is generated.

**Comment by milindm7** [comment]
Thanks Adam for answers
