### ISSUE TITLE
Should't it be 'false' for default value of--showHooks instead of 'failed'

### ISSUE THREAD

**Issue by SavitaMaurya** [adamgruber/mochawesome-report-generator#168]
https://github.com/adamgruber/mochawesome-report-generator#readme
<img width="1398" alt="Screenshot 2021-05-18 at 19 39 34" src="https://user-images.githubusercontent.com/47749634/118666557-e8397800-b810-11eb-9688-66349264a8c9.png">

Additionally, I tried with 'true' and still hooks are not shown in report. Any sample example available or any suggestions?

**Comment by adamgruber** [comment]
I've updated the README to list out the possible values for this option. They are:
- `failed`: show only failed hooks
- `always`: show all hooks
- `never`: hide all hooks
- `context`: show only hooks that have context
