### ISSUE TITLE
posibility of a 5.2.1 release with less strict validator version dependency 

### ISSUE THREAD

**Issue by evansrobert** [adamgruber/mochawesome-report-generator#173]
Hi, @adamgruber, 
### Issue Description

   I noticed that four vulnerabilities are introduced in **_mochawesome-report-generator@5.2.0_**:
     Vulnerability [SNYK-JS-VALIDATOR-1090600](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600), [SNYK-JS-VALIDATOR-1090599](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599), [SNYK-JS-VALIDATOR-1090601](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601) and [SNYK-JS-VALIDATOR-1090602](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602) affect package **_validator_** (versions:<13.6.0).    
The above vulnerable package is referenced by **_mochawesome-report-generator@5.2.0_** via:
`mochawesome-report-generator@5.2.0 ➔ validator@10.11.0`

Since **_mochawesome-report-generator@5.2.0_** ([239,503 downloads per week](https://www.npmjs.com/package/mochawesome-report-generator/v/5.2.0?activeTab=versions)) is referenced by **108** downstream projects (e.g., [mochawesome 6.2.2](https://www.npmjs.com/package/mochawesome) (latest version), [cypress-mochawesome-reporter 2.2.1](https://www.npmjs.com/package/cypress-mochawesome-reporter) (latest version), [@mocobaas/server-sdk 2.8.11](https://www.npmjs.com/package/@mocobaas/server-sdk) (latest version), [@pachyderm/scripts 0.5.4](https://www.npmjs.com/package/@pachyderm/scripts) (latest version), [npm-medgo-test 5.1.1-test-axel](https://www.npmjs.com/package/npm-medgo-test) (latest version)), the  above vulnerabilities can be propagated into these downstream projects and expose security threats to them via the following package dependency paths:
 (1)`@0xislamtaha/orchestrator@1.0.2 ➔ mochawesome-report-generator@5.2.0 ➔ validator@10.11.0`
  **......**

If **_mochawesome-report-generator@5.2.*_** removes the vulnerable package from the above version, then its fixed version can help downstream users decrease their pain.

**Given the large number of downstream users, could you help update your package to remove the vulnerability from mochawesome-report-generator@5.2.0 ?**

### Fixing suggestions

In **_mochawesome-report-generator@5.2.1_**, maybe you can kindly try to perform the following upgrade :
`validator ^10.11.0 ➔ ^13.6.0`; 

**Note:**
_**validator@13.6.0**(>=13.6.0) has fixed the vulnerability [SNYK-JS-VALIDATOR-1090600](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090600), [SNYK-JS-VALIDATOR-1090599](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090599), [SNYK-JS-VALIDATOR-1090601](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090601) and [SNYK-JS-VALIDATOR-1090602](https://snyk.io/vuln/SNYK-JS-VALIDATOR-1090602)._
Of course, you are welcome to share other ways to resolve the issue.

Best regards,
^_^

**Comment by adamgruber** [comment]
This should now be fixed in mochawesome v7 (includes mochawesome-report-generator v6)
