### ISSUE TITLE
Can the validator package be updated?

### ISSUE THREAD

**Issue by wronrohn** [adamgruber/mochawesome-report-generator#175]
https://github.com/adamgruber/mochawesome-report-generator/blob/29de865880c0a19c76d7c8e4a3135fd7cc1e6891/package.json#L87

version 10 of validator contains a security vulnerability. Can it be updated to its latest version here and also consumed in Mochawesome? since the vulnerability was traced from there.

**Comment by adamgruber** [comment]
Done. See mochawesome v7
