### ISSUE TITLE
run generator from code

### ISSUE THREAD

**Issue by geramy92** [adamgruber/mochawesome-report-generator#18]
Hey there,
I have simple question:
Currently docs are only telling running a command in cli.  For my case I i have multiple Test json files that can be simply merged by my code but then after running all tests and merge them I want to generate the html output with the generator. So now the question is if I can run this also from code base instead of cli.

greetings
Geramy92

**Comment by adamgruber** [comment]
Yes you can import this package and use it. The lib exports two functions, `create` and `createSync` so you can do something like this:

```js
import marge from 'mochawesome-report-generator';

marge.create(dataIn, options)
  .then(() => {
    // do something here if you want
  })
  .catch(e => {
    // handle any errors
  })
```

`create` will return a promise that resolves if the report was successfully created and saved to disk. `createSync` is the synchronous version.

**Comment by geramy92** [comment]
thanks
