### ISSUE TITLE
Call programmatically

### ISSUE THREAD

**Issue by Prophet32j** [adamgruber/mochawesome-report-generator#47]
I want to integrate this with Jest, but I don't see how to programmatically call marge. Is there a simple way to pass a JSON payload to marge without creating a new JSON file and calling via CLI?

**Comment by adamgruber** [comment]
Absolutely, that's how `mochawesome` works. You can require `mochawesome-report-generator` and call the `create()` method.

```js
const marge = require('mochawesome-report-generator');
marge.create(jsonPayload, options);
```

[Take a look at this](https://github.com/adamgruber/mochawesome/blob/master/src/mochawesome.js#L33) to see how `mochawesome` creates the report in its `done()` function.

I've been wanting to integrate mochawesome with other test frameworks like Karma and Jest. I'm curious to know what your integration plans are? Would you mind sharing whatever you come up with?

**Comment by Prophet32j** [comment]
My thought was to create a middleware script that converted the output of Jest into the input format of this reporter. Jest outputs a specific format, shown in the [docs](https://facebook.github.io/jest/docs/en/configuration.html#testresultsprocessor-string). So we know the exact inputs and outputs of both. Just a matter of wiring.

Later this could be expanded upon to take a configuration from the package.json just like [jest-html-reporter](https://github.com/Hargne/jest-html-reporter) does. Defaults, overrides, customizations.

**Comment by adamgruber** [comment]
Yeah I remember reading through Jest's docs a while back and seeing something about it's output. Not sure if _everything_ maps nicely but might not be too difficult. I'd be open to collaborating on it if you want.

**Comment by Prophet32j** [comment]
Is this something that will break the report generator as well? A well-defined API will greatly simplify integration with other test frameworks.

I am going to start work on this tomorrow morning. I will post my first pass and we can work for a good solution.

**Comment by adamgruber** [comment]
Yes, there are breaking changes with v3.

**Comment by Prophet32j** [comment]
is there anything that's required? The report has code snippets, but that's not present in the Jest output...among other things that aren't present.

**Comment by adamgruber** [comment]
This is the currently expected data in v3: https://github.com/adamgruber/mochawesome-report-generator/blob/3.0/bin/src/types.js

**Comment by Prophet32j** [comment]
what's your timeline for V3?

**Comment by adamgruber** [comment]
Most of the work for trimming the data is complete. However, there was some discussion in [this issue](https://github.com/adamgruber/mochawesome/issues/172) around what the data should look like. Some changes were suggested to facilitate the ability to merge reports. I'm not completely sold on the changes just yet but if I'm going to be changing the data structure at all, I'd prefer to do it just once. There are also a few other features I wanted to put into v3 so considering all this, a v3 release is probably a month or so out.

For what you're doing, however, if you build based on the current data structure in v2 I don't think it will require too much once v3 ships. It seems you'd like to get something working fairly quick so I'd say just work based on the current data, outlined [here](https://github.com/adamgruber/mochawesome-report-generator/blob/master/bin/src/types.js).

**Comment by Prophet32j** [comment]
ok so I don't know what's causing an error. The generator is not completely generating everything. Think you can take a look? Here's the code in a gist with the jest output and what was generated with my code as marge input: https://gist.github.com/Prophet32j/05a2ceda3743b9fd93e98e56a9227309

**Comment by adamgruber** [comment]
Looks like the input JSON isn't validating. If you run the `marge-input` JSON through the marge CLI you'll see a whole bunch of type warnings showing you what's incorrect / missing.

**Comment by Prophet32j** [comment]
```
Invalid value undefined supplied to /suites/suites/0/tests/0/err: Object
  Invalid value undefined supplied to /suites/suites/0/tests/0/isHook: Boolean
  Invalid value undefined supplied to /suites/suites/0/tests/1/err: Object
  Invalid value undefined supplied to /suites/suites/0/tests/1/isHook: Boolean
  Invalid value undefined supplied to /suites/suites/0/tests/2/err: Object
  Invalid value undefined supplied to /suites/suites/0/tests/2/isHook: Boolean
  Invalid value undefined supplied to /suites/suites/0/tests/3/err: Object
  Invalid value undefined supplied to /suites/suites/0/tests/3/isHook: Boolean
  Invalid value undefined supplied to /suites/suites/0/beforeHooks: Array<Struct{title: String, fullTitle: String, timedOut: Boolean, duration: Integer, state: ?TestState, speed: ?TestSpeed, pass: Boolean, fail: Boolean, pending: Boolean, code: String, err: Object, isRoot: Boolean, uuid: UUID, parentUUID: ?UUID, skipped: Boolean, context: ?String, isHook: Boolean}>
  Invalid value undefined supplied to /suites/suites/0/afterHooks: Array<Struct{title: String, fullTitle: String, timedOut: Boolean, duration: Integer, state: ?TestState, speed: ?TestSpeed, pass: Boolean, fail: Boolean, pending: Boolean, code: String, err: Object, isRoot: Boolean, uuid: UUID, parentUUID: ?UUID, skipped: Boolean, context: ?String, isHook: Boolean}>
  Invalid value undefined supplied to /suites/suites/0/passes/0/err: Object
  Invalid value undefined supplied to /suites/suites/0/passes/0/isHook: Boolean
  Invalid value undefined supplied to /suites/suites/0/passes/1/err: Object
  Invalid value undefined supplied to /suites/suites/0/passes/1/isHook: Boolean
  Invalid value undefined supplied to /suites/suites/0/passes/2/err: Object
  Invalid value undefined supplied to /suites/suites/0/passes/2/isHook: Boolean
  Invalid value undefined supplied to /suites/suites/0/passes/3/err: Object
  Invalid value undefined supplied to /suites/suites/0/passes/3/isHook: Boolean
  Invalid value undefined supplied to /suites/suites/0/totalPasses: Number
  Invalid value undefined supplied to /suites/suites/0/hasBeforeHooks: Boolean
  Invalid value undefined supplied to /suites/suites/0/hasAfterHooks: Boolean
  Invalid value undefined supplied to /suites/beforeHooks: Array<Struct{title: String, fullTitle: String, timedOut: Boolean, duration: Integer, state: ?TestState, speed: ?TestSpeed, pass: Boolean, fail: Boolean, pending: Boolean, code: String, err: Object, isRoot: Boolean, uuid: UUID, parentUUID: ?UUID, skipped: Boolean, context: ?String, isHook: Boolean}>
  Invalid value undefined supplied to /suites/afterHooks: Array<Struct{title: String, fullTitle: String, timedOut: Boolean, duration: Integer, state: ?TestState, speed: ?TestSpeed, pass: Boolean, fail: Boolean, pending: Boolean, code: String, err: Object, isRoot: Boolean, uuid: UUID, parentUUID: ?UUID, skipped: Boolean, context: ?String, isHook: Boolean}>
  Invalid value undefined supplied to /suites/totalPasses: Number
  Invalid value undefined supplied to /suites/hasBeforeHooks: Boolean
  Invalid value undefined supplied to /suites/hasAfterHooks: Boolean
  Invalid value undefined supplied to /allTests/0/err: Object
  Invalid value undefined supplied to /allTests/0/isHook: Boolean
  Invalid value undefined supplied to /allTests/1/err: Object
  Invalid value undefined supplied to /allTests/1/isHook: Boolean
  Invalid value undefined supplied to /allTests/2/err: Object
  Invalid value undefined supplied to /allTests/2/isHook: Boolean
  Invalid value undefined supplied to /allTests/3/err: Object
  Invalid value undefined supplied to /allTests/3/isHook: Boolean
  Invalid value undefined supplied to /allPasses/0/err: Object
  Invalid value undefined supplied to /allPasses/0/isHook: Boolean
  Invalid value undefined supplied to /allPasses/1/err: Object
  Invalid value undefined supplied to /allPasses/1/isHook: Boolean
  Invalid value undefined supplied to /allPasses/2/err: Object
  Invalid value undefined supplied to /allPasses/2/isHook: Boolean
  Invalid value undefined supplied to /allPasses/3/err: Object
  Invalid value undefined supplied to /allPasses/3/isHook: Boolean
  Invalid value "web-ui" supplied to /reportTitle: Nil
  Invalid value "ITADA Web UI Test Report" supplied to /reportPageTitle: Nil
```

Not sure why I'm getting these. I've hardcoded many of these values to a default value, and I'm still getting these.

**Comment by Prophet32j** [comment]
Done. The only thing that I don't have is all the code snippets that Mocha Awesome generates. That's not really a big deal because no one in management looks at that.

**Comment by adamgruber** [comment]
Would you mind sharing your code?

**Comment by Prophet32j** [comment]
I updated the gist above with my latest code that works. https://gist.github.com/Prophet32j/05a2ceda3743b9fd93e98e56a9227309

**Comment by Prophet32j** [comment]
@adamgruber have you made any progress on making drop ins for different testing frameworks?

**Comment by adamgruber** [comment]
Nope, it's not something I've been working on.

**Comment by belimm01** [comment]
@adamgruber Hi Adam, I'm new in mochawesome-report-generator and I'm using cypress. I run cypress with thiw options :  ```cypress.run({
        ...baseMap[bases.pop()] || {},
        spec: specs.join(),
        reporter: "../node_modules/mocha-multi-reporters/index.js",
        reporterOptions: {
            configFile: "mocha-config.json"
        }
    })
        .then((results) => {
            marge.create('../submodules/auth-ui/reports/html', null);
            if (results.failures > 0)
                return Promise.reject("Test failed");
        })
        .catch((err) => {
            console.log("Error: " + err);
        });```
My mocha-config.json : ```{
  "reporterEnabled": "mocha-junit-reporter, mochawesome",
  "mochaJunitReporterReporterOptions": {
    "mochaFile": "reports/junit/results.[hash].xml",
    "toConsole": false,
    "overwrite": false
  },
  "mochawesomeReporterOptions": {
    "reportDir": "reports/html",
    "overwrite": false,
    "html": false,
    "json": true
  }
}```
 I have several json reports in this directory ```../submodules/auth-ui/reports/html``` but when I execute the generated file by mochawesome-report-generator I have blank page. Please help me, sorry for my english :)

**Comment by adamgruber** [comment]
I'm not that familiar with how cypress works but mochawesome will always generate one report for each test run. You cannot combine multiple test runs into a single report.

**Comment by mjhea0** [comment]
I have mochawesome working here -> https://github.com/testdrivenio/cypress-mochawesome-s3

Essentially-

1. cypress runs
2. each spec generates a new report
3. a custom script combines each mochawesome json file and calculates the stats
4. html report is then generated
