### ISSUE TITLE
Expected/Actual reversed when using chai-subset

### ISSUE THREAD

**Issue by JeffML** [adamgruber/mochawesome-report-generator#48]
running mocha from CLI returns this result:
```
1) Checkout Test (JSON version) change shipping address:

      Uncaught AssertionError: expected { Object (company, firstName, ...) } to contain subset { Object (firstName, lastName, ...) }
      + expected - actual

       {
      -  "address1": "100 Peachtree St NW"
      -  "address2": ""
      -  "addressId": "0"
      -  "city": "Atlanta"
      -  "company": ""
      -  "country": "United States"
      -  "countryId": "249"
      -  "email": "nnn@nnn.com"
      -  "fax": ""
      -  "firstName": "Floo"
      -  "isResidential": ""
      -  "lastName": "Bit"
      -  "override": "1"
      -  "phone": "+1 800-800-2222"
      -  "phoneNight": [null]
      -  "state": "GA"
      -  "stateId": "24"
      -  "timeZone": "US/Eastern"
      -  "validated": "1"
      -  "zipcode": "30303-1906"
      +  "address1": "201 Columbine St Ste 100"
      +  "firstName": "Michael"
      +  "lastName": "McMaster"
       }
```
However, Mochawesome (generator or reporter, I'm not sure) shows the reverse:
https://www.dropbox.com/s/z6hsq271bk82ymr/Screenshot%202017-07-24%2015.04.14.png?dl=0

The specific assertion is:
```
                items[0].splits[0].address.should.containSubset( {
                    first_name:"Michael",
                    last_name:"McMaster",
                    address1:"201 Columbine St Ste 100",
                })
```

**Comment by adamgruber** [comment]
Can you confirm what versions of mochawesome you are running?

**Comment by JeffML** [comment]
I installed the latest. 2.3.0 as I recall.


Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Adam Gruber <notifications@github.com> Date: 7/24/17  4:08 PM  (GMT-08:00) To: adamgruber/mochawesome-report-generator <mochawesome-report-generator@noreply.github.com> Cc: Jeff Lowery <jlowery2663@gmail.com>, Author <author@noreply.github.com> Subject: Re: [adamgruber/mochawesome-report-generator] Expected/Actual
  reversed when using chai-subset (#48) 
Can you confirm what versions of mochawesome you are running?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/adamgruber/mochawesome-report-generator","title":"adamgruber/mochawesome-report-generator","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/adamgruber/mochawesome-report-generator"}},"updates":{"snippets":[{"icon":"PERSON","message":"@adamgruber in #48: Can you confirm what versions of mochawesome you are running?"}],"action":{"name":"View Issue","url":"https://github.com/adamgruber/mochawesome-report-generator/issues/48#issuecomment-317580936"}}}

**Comment by JeffML** [comment]
Sorry, my fault.  Looks like this was fixed. Closing.
