### ISSUE TITLE
Ability to customize default filtering when opening report

### ISSUE THREAD

**Issue by alerodm** [adamgruber/mochawesome-report-generator#50]
First of all, kudos for your project Adam, it has been really helpful for us.

About my proposal - We use mochawesome as the default reporter on our CI builds, but the report is usually reviewed only when builds fail at the regression stage. In that context, the most likely first action after opening the report is going to the filters to show only the failed ones, so it would be really nice to have that as a config option.

**Comment by adamgruber** [comment]
Thanks for the suggestion! I definitely see the value in adding an option for this. Not sure when I'll have time to get to it but I'll put it on the roadmap.

**Comment by alerodm** [comment]
No worries, I think we could give it a try and send a PR. Would you suggest any specific approach? I thought on a new flag such as `--default-filter failed,skipped`.

**Comment by adamgruber** [comment]
I think that approach would work. I'd probably just call it `filter` and you would just pass a comma separated list of filters you want enabled.

**Comment by adamgruber** [comment]
This is now available in 3.1.0
