### ISSUE TITLE
Ability to provide html snippets for test title

### ISSUE THREAD

**Issue by harishkswamy** [adamgruber/mochawesome-report-generator#53]
I would like to be able to make my test titles more descriptive for the business folks and would like the ability to add html snippets like `<ul>`, `<ol>` etc. Let me know if that is something you would consider adding to the library and I can provide a pull request. Also, any pointers as to how you would go about doing it would be appreciated as well, hoping it is a simple change to the `Test` component. Thanks.

**Comment by adamgruber** [comment]
@harishkswamy The test and suite titles come directly from what you put inside your `describe()` and `it()` functions. For example:
```js
describe('Suite Title', () => {
  it('Test Title',  () => {});
});
```
Mocha does some transformations on these titles to produce a "full" title which essentially just prepends test titles with any ancestor suite titles.

I don't really see a good reason or easy path to support markup in test/suite titles.

**Comment by harishkswamy** [comment]
Can you not change the `{ title }` in `test.jsx` to something like this? `<span dangerouslySetInnerHTML={{__html: title}} />`?

**Comment by adamgruber** [comment]
In theory sure but that opens things up to other issues, mainly it's not a good idea to use `dangerouslySetInnerHTML` unless you have a real need to do so. I just don't think there's a good enough case for it here.

If you need some way to add additional information to a test you could use [context](https://github.com/adamgruber/mochawesome/#adding-test-context).
