### ISSUE TITLE
Threoretical question: Programmatic usage and receiving results as objects

### ISSUE THREAD

**Issue by Xotabu4** [adamgruber/mochawesome-report-generator#89]
Hi! 

I doing some research about some reporter for mocha to be used inside AWS lambda function.

Since lambda has readonly file system, i need to receive JSON results as object, not as file. Then i will pass that json as response to caller, where i will grab all those objects, and generate HTML on caller side(host that ivoked lambda). 

Sure i understand that this is pretty crazy usage, most of all i will fork this repo and rewrite some parts to make that happen. But can you guys point me to right direction to make that fast?

So what i need 
- get results as object instead of JSON file. Probably i can monkey-patch some NodeJS fs functions to intercept saving to file call.

- Grab array of JSON results, and generate HTML from them

- Attachments and so on not planned yet.

**Comment by adamgruber** [comment]
The JSON is saved inside the `done` function. I suppose you could modify it to just send to stdout.
https://github.com/adamgruber/mochawesome/blob/master/src/mochawesome.js#L32

Once you have the JSON, you can use [mochawesome-report-generator](https://github.com/adamgruber/mochawesome-report-generator) to generate the HTML.

**Comment by Xotabu4** [comment]
@adamgruber Thank you! I will try this soon!
