### ISSUE TITLE
Pulling the generated link from unpkg.com returns 404

### ISSUE THREAD

**Issue by crafter999** [adamgruber/mochawesome-report-generator#90]
I don't know why but for some **strange** reasons I was trying to load assets from a CDN using the `cdn:true` option but my generated report was trying to load the following javascript file that didn't exist on unpkg.com and it was returning 404 **for a while**. After I regenerated my report and hit multiple times the refresh button It got fixed.
### File
https://unpkg.com/mochawesome-report-generator@3.1.1/dist/app.js

### Result
`Cannot find module "/dist/app.js" in package mochawesome-report-generator@3.1.1`

![mocha-report-bug](https://user-images.githubusercontent.com/27963519/35734032-5ae2114c-0828-11e8-9bd9-1ff2ca331756.PNG)

**Comment by adamgruber** [comment]
Definitely strange. Could have been a blip on unkpg.com. The URL that was generated in the report was correct. I'm going to close this as there's nothing much I can do here. Feel free to open another issues if this reoccurs.
