### ISSUE TITLE
Invalid value [] supplied to /allFailures: Nil

### ISSUE THREAD

**Issue by Devopssquadtechire** [adamgruber/mochawesome-report-generator#94]
Hi,
reporters: ['mochawesome'],
  reporterOptions: {
	    outputDir: test

The script produces a wdiomochawesome.json report file under xx output dir. The outcome of the format is as below.
==========================
Invalid value {
  "title": "sometitle"",
  "fullTitle": "I am logged in as some one",
  "timedOut": false,
  "duration": 0,
  "speed": "fast",
  "pass": true,
  "fail": false,
  "pending": false,
  "code": "",
  "isRoot": false,
  "uuid": "something",
  "parentUUID": "something",
  "skipped": false,
  "isHook": false,
  "context": "[{something}]",
  "state": "passed",
  "err": {}
} supplied to /suites/suites/0/passes/10: String
  Invalid value true supplied to /suites/suites/0/hasTests: Nil
  Invalid value false supplied to /suites/suites/0/hasSuites: Nil
  Invalid value 11 supplied to /suites/suites/0/totalTests: Nil
  Invalid value 11 supplied to /suites/suites/0/totalPasses: Nil
  Invalid value 0 supplied to /suites/suites/0/totalFailures: Nil
  Invalid value 0 supplied to /suites/suites/0/totalPending: Nil
  Invalid value 0 supplied to /suites/suites/0/totalSkipped: Nil
  Invalid value true supplied to /suites/suites/0/hasPasses: Nil
  Invalid value false supplied to /suites/suites/0/hasFailures: Nil
  Invalid value false supplied to /suites/suites/0/hasPending: Nil
  Invalid value false supplied to /suites/suites/0/hasSkipped: Nil
  Invalid value false supplied to /suites/suites/0/hasBeforeHooks: Nil
  Invalid value false supplied to /suites/suites/0/hasAfterHooks: Nil
  Invalid value false supplied to /suites/hasTests: Nil
  Invalid value true supplied to /suites/hasSuites: Nil
  Invalid value 0 supplied to /suites/totalTests: Nil
  Invalid value 0 supplied to /suites/totalPasses: Nil
  Invalid value 0 supplied to /suites/totalFailures: Nil
  Invalid value 0 supplied to /suites/totalPending: Nil
  Invalid value 0 supplied to /suites/totalSkipped: Nil
  Invalid value false supplied to /suites/hasPasses: Nil
  Invalid value false supplied to /suites/hasFailures: Nil
  Invalid value false supplied to /suites/hasPending: Nil
  Invalid value false supplied to /suites/hasSkipped: Nil
  Invalid value false supplied to /suites/hasBeforeHooks: Nil
  Invalid value false supplied to /suites/hasAfterHooks: Nil
  Invalid value [
  {
}
] supplied to /allPasses: Nil
  Invalid value [] supplied to /allFailures: Nil
=============================

Now when i produce the Mochawesomereport using the command "marge path xx/filename.json" within package.json it ends up without the Mochawesomereport file. Any suggestion?

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xxxx@1.1 test:generateMochawesomereport: `marge test/wdiomochaw
esome.json`
npm ERR! Exit status 1
npm ERR! xxxx@1.1 test:generateMochawesomereport: `marge test
esome.json`
npm ERR! Exit status 1

**Comment by Devopssquadtechire** [comment]
Is there any dependency between mochawesome output and mochawesomereport compilation logic?

**Comment by Devopssquadtechire** [comment]
I have tried with 3.0.x and 3.1.x 
 "mochawesome": "^3.0.2",
    "mochawesome-report-generator": "^3.0.1",
  

Am still getting same error. Do you have a JSON output file/format from Mochawesome that I can review , as actually I am not even able to verify if the mochawesome reporter output is properly generating in my case , as that would be the first step to debug.

You can see my sample mochawesome outcome here. Actually I am calling the Mochawesome inside Wdio framework config file.

### Invalid value {
"title": "sometitle"",
"fullTitle": "I am logged in as some one",
"timedOut": false,
"duration": 0,
"speed": "fast",
"pass": true,
"fail": false,
"pending": false,
"code": "",
"isRoot": false,
"uuid": "something",
"parentUUID": "something",
"skipped": false,
"isHook": false,
"context": "[{something}]",
"state": "passed",
"err": {}
} supplied to /suites/suites/0/passes/10: String

**Comment by Devopssquadtechire** [comment]
@tihmatsumoto - no not at all. Then I have moved to using allure reports.☺
If you come across a solution please feel free to post here.

Best Regards,
Chandrabose

**Comment by tihmatsumoto** [comment]
@Devopssquadtechire Thank you! Might consider moving to allure reports.

**Comment by davthu** [comment]
I had the same issue when using the generator with [wdio-mochawesome-reporter](https://github.com/fijijavis/wdio-mochawesome-reporter) until i found out that the reporter only supports version 2.3.2:

> NOTE wdio-mochawesome-reporter is NOT compatible with the 3.x versions of the mochawesome-report-generator

**Comment by RaghuveerA** [comment]
Thanks, @davthu It worked.
