### ISSUE TITLE
FSU release from 1.0.4 to 1.1.0 breaks older versions of Node

### ISSUE THREAD

**Issue by woodcockjosh** [adamgruber/mochawesome-report-generator#95]
FSU package just released an update which includes "...args" eg. the spread operator and breaks older versions of node. I would appreciate it if you locked to v1.0.4 and release a new version.

**Comment by adamgruber** [comment]
Closing this since it should now be fixed with fsu 1.1.1
https://github.com/velocityzen/fsu/issues/5
